"use client";
import {useEffect,useMemo,useState} from 'react';

type Product={id:string;name:string;price:number};
type Stock={productId:string;kg:number;cost:number;status:'LOAD'|'HOLD'|'CHECK'};
type Receipt={id:string;number:number;date:string;sourceType:string;sourceName:string;receiver:string;items:{productId:string;kg:number;price:number;sum:number}[];payments:{cash:number;kaspi:number;transfer:number;debt:number};total:number;status:string};
type Sale={id:string;number:number;date:string;buyer:string;items:{productId:string;kg:number;price:number;cogs:number;sum:number}[];payments:{cash:number;kaspi:number;transfer:number;debt:number};total:number;cogs:number};
type CashTx={id:string;date:string;direction:'IN'|'OUT';method:'CASH'|'KASPI'|'TRANSFER';category:string;amount:number;person:string;note:string};
type Employee={id:string;name:string};
type Process={id:string;number:number;date:string;employee:string;input:{productId:string;kg:number}[];output:{productId:string;kg:number;unit:number};pay:number;result:number};
type State={products:Product[];stock:Stock[];receipts:Receipt[];sales:Sale[];cash:CashTx[];employees:Employee[];processes:Process[];dayClosed:string[]};
const seedNames:string[]=["Медь", "Медь кабель", "Алюминий", "Латунь", "Ашка", "Диск", "Нерж", "Цинк", "Свинец", "Микс", "Дюр", "Мягкий", "Акб", "Банка", "Латунь Струшка"];
const money=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n)+' ₸';
const qty=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:3}).format(n)+' кг';
const today=()=>new Date().toISOString().slice(0,10);
const id=()=>crypto.randomUUID();
const emptyState=():State=>({products:seedNames.map((name,i)=>({id:'p'+(i+1),name,price:0})),stock:seedNames.map((_,i)=>({productId:'p'+(i+1),kg:0,cost:0,status:'HOLD'})),receipts:[],sales:[],cash:[],employees:[],processes:[],dayClosed:[]});

export default function LocalReceivingApp(){
 const [state,setState]=useState<State>(()=>emptyState()); const [tab,setTab]=useState('dashboard'); const [toast,setToast]=useState('');
 const [receipt,setReceipt]=useState<any>({sourceType:'Безымянный',sourceName:'',receiver:'',items:{},prices:{},payments:{cash:'',kaspi:'',transfer:'',debt:''}});
 const [sale,setSale]=useState<any>({buyer:'',items:{},prices:{},payments:{cash:'',kaspi:'',transfer:'',debt:''}});
 const [cash,setCash]=useState<any>({direction:'OUT',method:'CASH',category:'Обед',amount:'',person:'',note:''});
 const [close,setClose]=useState<any>({cash:'',kaspi:'',transfer:'',reason:''}); const [employeeName,setEmployeeName]=useState('');
 const [transfer,setTransfer]=useState<any>({}); const [process,setProcess]=useState<any>({employee:'',input:{},outputProduct:'p1',outputKg:'',outputUnit:'',pay:''});
 const save=(s:State)=>{setState(s);localStorage.setItem('receiving-v15-local',JSON.stringify(s));};
 useEffect(()=>{try{const r=localStorage.getItem('receiving-v15-local');if(r)setState(JSON.parse(r));}catch{}},[]);
 const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),2500)};
 const totals=useMemo(()=>{let kg=0,cost=0;for(const s of state.stock){kg+=s.kg;cost+=s.cost}return {kg,cost}},[state.stock]);
 const todayReceipts=state.receipts.filter(r=>r.date===today()); const todaySales=state.sales.filter(r=>r.date===today());
 const cashBal=useMemo(()=>state.cash.reduce((s,t)=>s+(t.direction==='IN'?t.amount:-t.amount),0),[state.cash]);
 const paymentTotal=(p:any)=>Object.values(p||{}).reduce((a,v)=>a+Number(v||0),0);
 const receiptItems=()=>Object.entries(receipt.items).map(([pid,v]:any)=>({productId:pid,kg:Number(v||0),price:Number(receipt.prices[pid]||0),sum:Number(v||0)*Number(receipt.prices[pid]||0)})).filter(x=>x.kg>0);
 const saleItems=()=>Object.entries(sale.items).map(([pid,v]:any)=>({productId:pid,kg:Number(v||0),price:Number(sale.prices[pid]||0)})).filter((x:any)=>x.kg>0).map((x:any)=>{const st=state.stock.find(s=>s.productId===x.productId);const c=(st?.kg?st.cost/st.kg:0);return {...x,cogs:x.kg*c,sum:x.kg*x.price}});
 function addReceipt(){const items=receiptItems();const total=items.reduce((s,i)=>s+i.sum,0);const pay={cash:Number(receipt.payments.cash||0),kaspi:Number(receipt.payments.kaspi||0),transfer:Number(receipt.payments.transfer||0),debt:Number(receipt.payments.debt||0)};if(!items.length)return notify('Добавь товар и кг');if(Math.abs(paymentTotal(pay)-total)>0.01)return notify('Расчёт не сходится с суммой приёмки');const ns={...state,receipts:[{id:id(),number:state.receipts.length+1,date:today(),sourceType:receipt.sourceType,sourceName:receipt.sourceName,receiver:receipt.receiver,items,payments:pay,total,status:'CONFIRMED'},...state.receipts],stock:state.stock.map(s=>{const it=items.find(i=>i.productId===s.productId);if(!it)return s;return {productId:s.productId,kg:s.kg+it.kg,cost:s.cost+it.sum,status:s.status};}),cash:[...state.cash,...(['cash','kaspi','transfer'] as const).flatMap((m)=>pay[m]?{id:id(),date:today(),direction:'IN' as const,method:m==='cash'?'CASH':m==='kaspi'?'KASPI':'TRANSFER' as any,category:'Оплата приёмки',amount:pay[m],person:receipt.sourceName,note:''}:[]) ]};save(ns);setReceipt({sourceType:'Безымянный',sourceName:'',receiver:'',items:{},prices:{},payments:{cash:'',kaspi:'',transfer:'',debt:''}});notify('Приёмка сохранена ✅');}
 function addSale(){const items=saleItems();const total=items.reduce((s,i)=>s+i.sum,0);const cogs=items.reduce((s,i)=>s+i.cogs,0);const pay={cash:Number(sale.payments.cash||0),kaspi:Number(sale.payments.kaspi||0),transfer:Number(sale.payments.transfer||0),debt:Number(sale.payments.debt||0)};if(!items.length)return notify('Добавь товар и кг');if(Math.abs(paymentTotal(pay)-total)>0.01)return notify('Расчёт клиента не сходится');for(const i of items){const st=state.stock.find(s=>s.productId===i.productId);if(!st||st.kg<i.kg)return notify('Недостаточный остаток на пункте');}const ns={...state,sales:[{id:id(),number:state.sales.length+1,date:today(),buyer:sale.buyer,items,payments:pay,total,cogs},...state.sales],stock:state.stock.map(s=>{const it=items.find(i=>i.productId===s.productId);return it?{...s,kg:s.kg-it.kg,cost:Math.max(0,s.cost-it.cogs)}:s;}),cash:[...state.cash,...(['cash','kaspi','transfer'] as const).flatMap((m)=>pay[m]?{id:id(),date:today(),direction:'IN' as const,method:m==='cash'?'CASH':m==='kaspi'?'KASPI':'TRANSFER' as any,category:'Оплата прямой отгрузки',amount:pay[m],person:sale.buyer,note:''}:[]) ]};save(ns);setSale({buyer:'',items:{},prices:{},payments:{cash:'',kaspi:'',transfer:'',debt:''}});notify('Прямая отгрузка сохранена ✅');}
 function addCash(){const amount=Number(cash.amount||0);if(amount<=0)return notify('Введите сумму');const tx={id:id(),date:today(),direction:cash.direction,method:cash.method,category:cash.category,amount,person:cash.person,note:cash.note};save({...state,cash:[tx,...state.cash]});setCash({...cash,amount:'',note:''});notify('Операция кассы добавлена');}
 function closeDay(){const actual=Number(close.cash||0)+Number(close.kaspi||0)+Number(close.transfer||0);const expected=cashBal;const diff=actual-expected;save({...state,dayClosed:[today(),...state.dayClosed.filter(d=>d!==today())]});notify(`День ${diff===0?'закрыт ✅':'закрыт с разницей '+money(diff)}`);}
 function addEmployee(){if(!employeeName.trim())return;save({...state,employees:[...state.employees,{id:id(),name:employeeName.trim()}]});setEmployeeName('');notify('Сотрудник добавлен');}
 function setStatus(pid:string,status:Stock['status']){save({...state,stock:state.stock.map(s=>s.productId===pid?{...s,status}:s)});}
 function transferToHangar(){const moved=Object.entries(transfer).map(([pid,v])=>({pid,kg:Number(v||0)})).filter(x=>x.kg>0);if(!moved.length)return notify('Укажи что перемещаем');for(const m of moved){const st=state.stock.find(s=>s.productId===m.pid);if(!st||st.kg<m.kg)return notify('Недостаточно остатка');}save({...state,stock:state.stock.map(s=>{const m=moved.find(x=>x.pid===s.productId);return m?{...s,kg:s.kg-m.kg,cost:Math.max(0,s.cost-(s.kg?m.kg*(s.cost/s.kg):0))}:s;})});setTransfer({});notify('Перемещение подготовлено ✅ (в локальной версии Ангар не подключён)');}
 function addProcess(){const ins=Object.entries(process.input).map(([pid,v])=>({productId:pid,kg:Number(v||0)})).filter(x=>x.kg>0);const outKg=Number(process.outputKg||0);const unit=Number(process.outputUnit||0);if(!ins.length||!outKg)return notify('Заполни сырьё и результат');let inputCost=0;for(const x of ins){const st=state.stock.find(s=>s.productId===x.productId);if(!st||st.kg<x.kg)return notify('Недостаточно сырья');inputCost += st.kg ? x.kg*(st.cost/st.kg):0;}const result=outKg*unit-inputCost-Number(process.pay||0);const ns={...state,stock:state.stock.map(s=>{const x=ins.find(i=>i.productId===s.productId);return x?{...s,kg:s.kg-x.kg,cost:Math.max(0,s.cost-inputCost)}:s;}),processes:[{id:id(),number:state.processes.length+1,date:today(),employee:state.employees.find(e=>e.id===process.employee)?.name||'',input:ins,output:{productId:process.outputProduct,kg:outKg,unit},pay:Number(process.pay||0),result},...state.processes]};save(ns);notify(`Переработка проведена. Результат ${money(result)}`);}
 const getName=(pid:string)=>state.products.find(p=>p.id===pid)?.name||pid;
 return <main className="receiving-app"><header className="topbar"><div><b>📥 Пункт приёмки</b><span className="muted">Локальная версия · данные сохраняются на этом компьютере</span></div><span className="badge">{today()}</span></header>
 <nav className="tabs">{[['dashboard','Главная'],['receipt','Новая приёмка'],['stock','Склад пункта'],['sale','Прямая продажа'],['transfer','В Ангар'],['cash','Касса'],['employees','Сотрудники'],['processing','Переработка'],['closing','Закрытие дня']].map(([k,n])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{n}</button>)}</nav>
 <section className="content">{tab==='dashboard'&&<><div className="kpis"><div><small>Сегодня принято</small><strong>{money(todayReceipts.reduce((s,r)=>s+r.total,0))}</strong><span>{todayReceipts.reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.kg,0),0).toFixed(0)} кг</span></div><div><small>Прямая отгрузка</small><strong>{money(todaySales.reduce((s,r)=>s+r.total,0))}</strong><span>{todaySales.reduce((s,r)=>s+r.items.reduce((a,i)=>a+i.kg,0),0).toFixed(0)} кг</span></div><div><small>Склад пункта</small><strong>{money(totals.cost)}</strong><span>{totals.kg.toFixed(0)} кг</span></div><div><small>Касса по журналу</small><strong>{money(cashBal)}</strong><span>{state.dayClosed.includes(today())?'День закрыт':'День открыт'}</span></div></div><div className="panel"><h2>Что сейчас делать</h2><div className="quick"><button onClick={()=>setTab('receipt')}>＋ Новая приёмка</button><button onClick={()=>setTab('sale')}>💰 Продать с пункта</button><button onClick={()=>setTab('transfer')}>🚚 Подготовить в Ангар</button><button onClick={()=>setTab('closing')}>🔒 Закрыть день</button></div></div><div className="panel"><h2>Последние приёмки</h2>{state.receipts.slice(0,8).map(r=><div className="row" key={r.id}><b>№{r.number}</b><span>{r.sourceName||'Безымянный'}</span><span>{money(r.total)}</span><span>{r.date}</span></div>)}</div></>}
 {tab==='receipt'&&<Panel title="Новая приёмка"><label>Кто принёс<select value={receipt.sourceType} onChange={e=>setReceipt({...receipt,sourceType:e.target.value})}><option>Безымянный</option><option>Физлицо</option><option>Контрагент</option><option>Сотрудник</option><option>Другое</option></select></label><label>Имя/описание<input value={receipt.sourceName} onChange={e=>setReceipt({...receipt,sourceName:e.target.value})}/></label><label>Приёмщик<input value={receipt.receiver} onChange={e=>setReceipt({...receipt,receiver:e.target.value})}/></label><div className="grid">{state.products.map(p=><div className="product-card" key={p.id}><b>{p.name}</b><label>Кг<input type="number" inputMode="decimal" value={receipt.items[p.id]||''} onChange={e=>setReceipt({...receipt,items:{...receipt.items,[p.id]:e.target.value}})}/></label><label>Цена<input type="number" inputMode="decimal" value={receipt.prices[p.id]||''} onChange={e=>setReceipt({...receipt,prices:{...receipt.prices,[p.id]:e.target.value}})}/></label></div>)}</div><Payments state={receipt.payments} setState={(payments:any)=>setReceipt({...receipt,payments})}/><button className="primary big" onClick={addReceipt}>Сохранить приёмку</button></Panel>}
 {tab==='stock'&&<Panel title="Склад пункта"><table><thead><tr><th>Товар</th><th>Кг</th><th>Средняя себестоимость</th><th>Стоимость</th><th>Статус</th></tr></thead><tbody>{state.stock.map(s=><tr key={s.productId}><td>{getName(s.productId)}</td><td>{s.kg.toFixed(3)}</td><td>{money(s.kg?s.cost/s.kg:0)}</td><td>{money(s.cost)}</td><td><select value={s.status} onChange={e=>setStatus(s.productId,e.target.value as any)}><option value="LOAD">🟢 Грузить</option><option value="HOLD">🟡 Пока не грузить</option><option value="CHECK">🔴 Проверить</option></select></td></tr>)}</tbody></table></Panel>}
 {tab==='sale'&&<Panel title="Прямая отгрузка с пункта"><label>Кому продаём<input value={sale.buyer} onChange={e=>setSale({...sale,buyer:e.target.value})}/></label><div className="grid">{state.stock.filter(s=>s.kg>0).map(s=>{const p=state.products.find(p=>p.id===s.productId)!;const avg=s.kg?s.cost/s.kg:0;return <div className="product-card" key={p.id}><b>{p.name}</b><small>Доступно {s.kg.toFixed(3)} кг · себестоимость {money(avg)}/кг</small><label>Кг<input type="number" inputMode="decimal" value={sale.items[p.id]||''} onChange={e=>setSale({...sale,items:{...sale.items,[p.id]:e.target.value}})}/></label><label>Цена продажи<input type="number" inputMode="decimal" value={sale.prices[p.id]||''} onChange={e=>setSale({...sale,prices:{...sale.prices,[p.id]:e.target.value}})}/></label></div>})}</div><Payments state={sale.payments} setState={(payments:any)=>setSale({...sale,payments})}/><button className="primary big" onClick={addSale}>Отгрузить напрямую</button></Panel>}
 {tab==='transfer'&&<Panel title="Что переместить в Ангар"><p className="muted">Локальная версия: операция пока уменьшает склад пункта и фиксирует намерение; связь с реальным Ангаром подключим позже отдельным модулем.</p><div className="grid">{state.stock.filter(s=>s.kg>0).map(s=><div className="product-card" key={s.productId}><b>{getName(s.productId)}</b><small>Остаток {s.kg.toFixed(3)} кг · {money(s.kg?s.cost/s.kg:0)}/кг</small><input type="number" inputMode="decimal" placeholder="Сколько в Ангар" value={transfer[s.productId]||''} onChange={e=>setTransfer({...transfer,[s.productId]:e.target.value})}/></div>)}</div><button className="primary big" onClick={transferToHangar}>Подготовить перемещение</button></Panel>}
 {tab==='cash'&&<Panel title="Касса"><div className="kpis small"><div><small>Баланс</small><strong>{money(cashBal)}</strong></div></div><div className="form-grid"><label>Тип<select value={cash.direction} onChange={e=>setCash({...cash,direction:e.target.value})}><option value="IN">Приход</option><option value="OUT">Расход</option></select></label><label>Способ<select value={cash.method} onChange={e=>setCash({...cash,method:e.target.value})}><option value="CASH">Наличные</option><option value="KASPI">Kaspi</option><option value="TRANSFER">Перевод</option></select></label><label>Категория<input value={cash.category} onChange={e=>setCash({...cash,category:e.target.value})}/></label><label>Сумма<input type="number" inputMode="decimal" value={cash.amount} onChange={e=>setCash({...cash,amount:e.target.value})}/></label><label>Кому/от кого<input value={cash.person} onChange={e=>setCash({...cash,person:e.target.value})}/></label><label>Комментарий<input value={cash.note} onChange={e=>setCash({...cash,note:e.target.value})}/></label></div><button className="primary" onClick={addCash}>Добавить в кассу</button><div className="list">{state.cash.slice(0,50).map(t=><div className="row" key={t.id}><b>{t.direction==='IN'?'+':'−'} {money(t.amount)}</b><span>{t.method}</span><span>{t.category}</span><span>{t.person}</span><span>{t.date}</span></div>)}</div></Panel>}
 {tab==='employees'&&<Panel title="Сотрудники"><div className="inline"><input placeholder="Имя сотрудника" value={employeeName} onChange={e=>setEmployeeName(e.target.value)}/><button onClick={addEmployee}>Добавить</button></div><div className="list">{state.employees.map(e=><div className="row" key={e.id}><b>{e.name}</b></div>)}</div></Panel>}
 {tab==='processing'&&<Panel title="Переработка"><label>Сотрудник<select value={process.employee} onChange={e=>setProcess({...process,employee:e.target.value})}><option value="">Выбери</option>{state.employees.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><div className="grid">{state.stock.filter(s=>s.kg>0).map(s=><div className="product-card" key={s.productId}><b>Сырьё: {getName(s.productId)}</b><input type="number" inputMode="decimal" placeholder="Кг" value={process.input[s.productId]||''} onChange={e=>setProcess({...process,input:{...process.input,[s.productId]:e.target.value}})}/></div>)}</div><label>Результат<select value={process.outputProduct} onChange={e=>setProcess({...process,outputProduct:e.target.value})}>{state.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-grid"><label>Результат, кг<input type="number" inputMode="decimal" value={process.outputKg} onChange={e=>setProcess({...process,outputKg:e.target.value})}/></label><label>Цена результата/кг<input type="number" inputMode="decimal" value={process.outputUnit} onChange={e=>setProcess({...process,outputUnit:e.target.value})}/></label><label>Оплата сотруднику<input type="number" inputMode="decimal" value={process.pay} onChange={e=>setProcess({...process,pay:e.target.value})}/></label></div><button className="primary big" onClick={addProcess}>Провести переработку</button><div className="list">{state.processes.map(p=><div className="row" key={p.id}><b>№{p.number}</b><span>{p.employee}</span><span>{money(p.result)}</span><span>{p.date}</span></div>)}</div></Panel>}
 {tab==='closing'&&<Panel title="Закрытие дня"><div className="kpis"><div><small>По журналу кассы</small><strong>{money(cashBal)}</strong></div><div><small>Сегодня приёмка</small><strong>{money(todayReceipts.reduce((s,r)=>s+r.total,0))}</strong></div><div><small>Сегодня продажа</small><strong>{money(todaySales.reduce((s,r)=>s+r.total,0))}</strong></div><div><small>Статус</small><strong>{state.dayClosed.includes(today())?'✅ Закрыт':'🟡 Открыт'}</strong></div></div><div className="form-grid"><label>Фактические наличные<input type="number" inputMode="decimal" value={close.cash} onChange={e=>setClose({...close,cash:e.target.value})}/></label><label>Фактический Kaspi<input type="number" inputMode="decimal" value={close.kaspi} onChange={e=>setClose({...close,kaspi:e.target.value})}/></label><label>Фактический перевод<input type="number" inputMode="decimal" value={close.transfer} onChange={e=>setClose({...close,transfer:e.target.value})}/></label><label>Комментарий расхождения<input value={close.reason} onChange={e=>setClose({...close,reason:e.target.value})}/></label></div><button className="primary big" onClick={closeDay}>Закрыть день</button></Panel>}
 </section>{toast&&<div className="toast">{toast}</div>}</main>
}
function Panel(p:any){return <div className="panel"><div className="panel-head"><h2>{p.title}</h2></div>{p.children}</div>}
function Payments({state,setState}:{state:any;setState:(x:any)=>void}){return <div className="panel sub"><h3>Расчёт</h3><div className="form-grid"><label>Наличные<input type="number" inputMode="decimal" value={state.cash} onChange={e=>setState({...state,cash:e.target.value})}/></label><label>Kaspi<input type="number" inputMode="decimal" value={state.kaspi} onChange={e=>setState({...state,kaspi:e.target.value})}/></label><label>Перевод<input type="number" inputMode="decimal" value={state.transfer} onChange={e=>setState({...state,transfer:e.target.value})}/></label><label>Долг<input type="number" inputMode="decimal" value={state.debt} onChange={e=>setState({...state,debt:e.target.value})}/></label></div></div>}
