begin;
create or replace function public.import_legacy_operation(p_workspace_id uuid,p_operation_id uuid,p_legacy_operation_id text,p_legacy_parent_operation_id text,p_operation_number bigint,p_operation_date date,p_type public.operation_type,p_role public.operation_role,p_contractor_id uuid,p_created_at timestamptz,p_items jsonb) returns uuid language plpgsql security definer set search_path=public,pg_catalog as $$
declare x jsonb; v_product uuid; begin
 insert into public.operations(id,workspace_id,legacy_operation_id,legacy_parent_operation_id,operation_number,operation_date,type,role,contractor_id,created_at) values(p_operation_id,p_workspace_id,p_legacy_operation_id,p_legacy_parent_operation_id,p_operation_number,p_operation_date,p_type,p_role,p_contractor_id,p_created_at) on conflict(id) do nothing;
 for x in select * from jsonb_array_elements(p_items) loop select id into v_product from public.products where workspace_id=p_workspace_id and lower(name)=lower(x->>'name'); if v_product is null then raise exception 'Товар не найден: %',x->>'name'; end if; insert into public.operation_items(workspace_id,operation_id,product_id,quantity_kg,unit_price,waste_kg) values(p_workspace_id,p_operation_id,v_product,(x->>'kg')::numeric,(x->>'price')::numeric,coalesce((x->>'wasteKg')::numeric,0)) on conflict(operation_id,product_id) do nothing; end loop; return p_operation_id; end; $$;
create or replace function public.resolve_legacy_parents(p_workspace_id uuid) returns void language plpgsql security definer set search_path=public,pg_catalog as $$ begin update public.operations child set parent_operation_id=parent.id from public.operations parent where child.workspace_id=p_workspace_id and child.legacy_parent_operation_id is not null and parent.workspace_id=p_workspace_id and parent.legacy_operation_id=child.legacy_parent_operation_id; end; $$;
revoke all on function public.import_legacy_operation(uuid,uuid,text,text,bigint,date,public.operation_type,public.operation_role,uuid,timestamptz,jsonb) from public; grant execute on function public.import_legacy_operation(uuid,uuid,text,text,bigint,date,public.operation_type,public.operation_role,uuid,timestamptz,jsonb) to service_role;
revoke all on function public.resolve_legacy_parents(uuid) from public; grant execute on function public.resolve_legacy_parents(uuid) to service_role;
commit;
